FROM mhart/alpine-node:14.16.1

WORKDIR /app
COPY . .
RUN printf $'\n\
set -e\n\  
if [[ "$RUN_SEEDER" == "true" ]]; then \n\
    until nc -z -v backend:$BACKEND_PORT; do\n\
        >&2 echo "BACKEND is unavailable - sleeping"\n\
        sleep 1\n\
    done\n\  
    >&2 echo "BACKEND is up - executing seeder"\n\
    exec "$@" \n\
fi;\n' > /app/waitfor.sh;

RUN npm ci
CMD [ "sh", "/app/waitfor.sh", "node", "seeder.js" ]
